### ISSUE TITLE
upgrade dependencies to the latest versions

### ISSUE THREAD

**Issue by luolonghao** [lakejs/lake#11]
https://github.com/raineorshine/npm-check-updates

```bash
$ ncu
```

- [x] @rollup/plugin-typescript         ^11.1.6  →  ^12.1.1
- [x]  @types/chai                       ^4.3.20  →   ^5.0.0
- [ ]  @typescript-eslint/eslint-plugin  ^7.18.0  →  ^8.11.0 : waiting for [eslint v9 support](https://github.com/airbnb/javascript/issues/2961)
- [ ]  @typescript-eslint/parser         ^7.18.0  →  ^8.11.0: waiting for [eslint v9 support](https://github.com/airbnb/javascript/issues/2961)
- [x]  chai                               ^4.5.0  →   ^5.1.2
- [x]  eslint                            ^8.57.1  →  ^9.13.0 : waiting for [eslint v9 support](https://github.com/airbnb/javascript/issues/2961)

**Comment by luolonghao** [comment]
remove "eslint-config-airbnb-base", see https://github.com/lakejs/lake/commit/c0623e93c321b95801364aa93edd6b28e697260c

**Comment by luolonghao** [comment]
Now using `@antfu/eslint-config`. It supports the latest version of ESLint and is easy to use.
