### ISSUE TITLE
To-do List (version 0.1.0)

### ISSUE THREAD

**Issue by luolonghao** [lakejs/lake#2]
First stage: from 2023-08-01 to 2023-10-16

- [x] registering domains (lakejs.com, lakejs.org)
- [X] creating Github organization and repository (github.com/lakejs/lake)
- [X] publishing npm package (lake-lib)
- [X] initializing project (TypeScript, ESLint, Rollup, pnpm, etc.)
- [X] utils
- [X] models
- [X] operations
- [X] plugins
- [X] history (undo, redo)
- [X] HTML parser
- [X] text parser
- [X] paste
- [X] select all
- [x] heading
- [X] blockquote
- [X] list (numbered list, bulleted list, checklist)
- [X] align (left, center, right, justify)
- [X] indent (increase, decrease)
- [X] bold
- [X] italic
- [X] underline
- [X] strikethrough
- [X] subscript
- [X] superscript
- [X] code
- [X] font family
- [X] font size
- [X] font color
- [X] highlight
- [X] remove format

**Comment by luolonghao** [comment]
* [ ] improve paste
* [ ] improve enter keystroke
* [ ] improve tab keystroke
* [ ] improve backspace keystroke
* [ ] markdown shortcuts
* [ ] format painter
* [ ] hr
* [ ] image
* [ ] link
* [ ] examples (styles, toolbar, icons, etc.)
* [ ] documentation
* [ ] lake-react
* [ ] website

**Comment by luolonghao** [comment]
- [ ] refactor: move the get methods of operations into range object
- [ ] feat: render all boxes after the value was set

**Comment by luolonghao** [comment]
- [ ] fix(enter): fix(enter): throw an error when the cursor is outside the end of the box
- [ ] feat(box): add a class when the box is selected

**Comment by luolonghao** [comment]
- [ ] fix(box): can input text in both strips of box

**Comment by luolonghao** [comment]
- [ ] fix: operations have wrong behavior when the cursor is at both side of the box
- [ ] fix: bookmark doesn't support box

**Comment by luolonghao** [comment]
- [ ] fix: update unmodified content when redoing
- [ ] fix(tab-key): incorrect behavior of about box

**Comment by luolonghao** [comment]
- [ ] refactor(box): need to be clear about focused / selected box
- [ ] fix(box): cursor movement around inline-box by left / right key

**Comment by luolonghao** [comment]
- [ ] fix(list): numbered list shows wrong number after indentation

**Comment by luolonghao** [comment]
- [ ]  fix(list): indent attribute was removed when changing list type

**Comment by luolonghao** [comment]
- [ ] fix(list): bulleted list shows wrong marker after indentation

**Comment by luolonghao** [comment]
- [ ] upgrade CodeMirror version
- [ ] publish dist to unpkg.com

**Comment by luolonghao** [comment]
- [ ] extract Button, Dropdown, UploadButton, ColorPicker and add their test cases
- [ ] publish npm package & dist files
- [ ] complete examples

**Comment by luolonghao** [comment]
- [ ] support i18n
- [ ] support custom toolbar (headless editor)
- [ ] box insertion (`/` shortcut, toolbar icon)
- [ ] complete website

**Comment by luolonghao** [comment]
- [ ] complete website

**Comment by luolonghao** [comment]
- [ ] website: index
- [ ] website: examples
- [ ] website: guide
- [ ] website: reference
